"""
Base strategy interface.
All trading strategies must inherit from this class.
"""

import asyncio
import time
from abc import ABC, abstractmethod
from typing import List, Optional, Dict, Any
from dataclasses import dataclass, field
from enum import Enum

from data.indicators import IndicatorEngine, IndicatorState
from data.price_feed import PriceTick
from data.orderbook import OrderBook
from execution.sdk_executor import Order, OrderSide, OrderType
from utils.logger import log


class Signal(str, Enum):
    """Trading signal types."""
    STRONG_BUY = "STRONG_BUY"
    BUY = "BUY"
    WEAK_BUY = "WEAK_BUY"
    NEUTRAL = "NEUTRAL"
    WEAK_SELL = "WEAK_SELL"
    SELL = "SELL"
    STRONG_SELL = "STRONG_SELL"


@dataclass
class TradeSignal:
    """A trading signal generated by a strategy."""
    signal: Signal = Signal.NEUTRAL
    pair: str = ""
    confidence: float = 0.0  # 0.0 to 1.0
    suggested_side: Optional[OrderSide] = None
    suggested_price: float = 0.0
    suggested_quantity: float = 0.0
    suggested_leverage: int = 1
    stop_loss: float = 0.0
    take_profit: float = 0.0
    reason: str = ""
    strategy_name: str = ""
    timestamp: float = field(default_factory=time.time)
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_actionable(self) -> bool:
        """True if this signal suggests entering a position."""
        return self.signal in (
            Signal.STRONG_BUY, Signal.BUY,
            Signal.STRONG_SELL, Signal.SELL,
        )

    @property
    def is_bullish(self) -> bool:
        return self.signal in (Signal.STRONG_BUY, Signal.BUY, Signal.WEAK_BUY)

    @property
    def is_bearish(self) -> bool:
        return self.signal in (Signal.STRONG_SELL, Signal.SELL, Signal.WEAK_SELL)


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.
    Subclasses implement the `analyze` method to generate trading signals.
    """

    def __init__(self, name: str, pairs: List[str]):
        self.name = name
        self.pairs = pairs
        self.enabled = True
        self._indicators: Dict[str, IndicatorEngine] = {}
        self._last_signal: Dict[str, TradeSignal] = {}
        self._last_trade_time: Dict[str, float] = {}
        self._trade_count: int = 0
        self._cooldown_seconds: float = 5.0

    def get_indicator_engine(self, pair: str) -> IndicatorEngine:
        """Get or create indicator engine for a pair."""
        if pair not in self._indicators:
            self._indicators[pair] = IndicatorEngine()
        return self._indicators[pair]

    def update_indicators(self, tick: PriceTick) -> Optional[IndicatorState]:
        """Update indicators with a new price tick."""
        if tick.pair not in self.pairs:
            return None
        engine = self.get_indicator_engine(tick.pair)
        return engine.update(
            price=tick.price,
            high=tick.high if tick.high > 0 else None,
            low=tick.low if tick.low > 0 else None,
            volume=tick.volume,
            timestamp=tick.timestamp,
        )

    def can_trade(self, pair: str) -> bool:
        """Check if cooldown has elapsed for this pair."""
        if not self.enabled:
            return False
        last_time = self._last_trade_time.get(pair, 0)
        return (time.time() - last_time) >= self._cooldown_seconds

    def record_trade(self, pair: str):
        """Record that a trade was executed for cooldown tracking."""
        self._last_trade_time[pair] = time.time()
        self._trade_count += 1

    @abstractmethod
    async def analyze(
        self,
        pair: str,
        tick: PriceTick,
        indicators: IndicatorState,
        orderbook: Optional[OrderBook] = None,
    ) -> TradeSignal:
        """
        Analyze current market conditions and generate a trading signal.
        This is the core strategy logic that subclasses must implement.
        """
        pass

    async def on_tick(
        self,
        tick: PriceTick,
        orderbook: Optional[OrderBook] = None,
    ) -> Optional[TradeSignal]:
        """
        Process a price tick — update indicators and generate signal.
        Called by the engine on every price update.
        """
        if tick.pair not in self.pairs:
            return None

        if not self.enabled:
            return None

        # Update indicators
        state = self.update_indicators(tick)
        if state is None:
            return None

        # Check if indicators have warmed up
        engine = self.get_indicator_engine(tick.pair)
        if not engine.ready:
            return None

        # Check cooldown
        if not self.can_trade(tick.pair):
            return None

        # Run strategy analysis
        try:
            signal = await self.analyze(tick.pair, tick, state, orderbook)
            signal.strategy_name = self.name
            self._last_signal[tick.pair] = signal
            return signal
        except Exception as e:
            log.error(f"Strategy {self.name} error on {tick.pair}: {e}")
            return None

    def get_last_signal(self, pair: str) -> Optional[TradeSignal]:
        """Get the most recent signal for a pair."""
        return self._last_signal.get(pair)

    def __repr__(self) -> str:
        return f"{self.name}(pairs={self.pairs}, trades={self._trade_count})"
